name: Deploy OTP Page

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace secret in HTML
        run: |
          mkdir -p dist
          sed "s/{{OTP_SECRET}}/${{ secrets.OTP_SECRET }}/g" index.html > dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist